version: '2'
services:
  web:
    extends:
      file: docker-compose.common.yml
      service: web
    build:
      context: .
      args:
        NPM_REGISTRY: http://sinopia.view.build
        PACKAGE_INSTALLER: yarn
    command: 'bash -c ''npm start'''
    ports:
      - 3000
    environment:
      NODE_ENV: 'production'
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: sam@madeinhaus.com
